### ISSUE TITLE
Null pointer exception when vcard.postalInfo is hidden

### ISSUE THREAD

**Issue by TheRedTrainer** [NICMx/rdap-core#2]
If a user configure the privacy settings for postalInfo property in vcard.properties as "none" in order to hide the value to every user, and a client request any data that involves a vcard array (for example, a domain), the server returns a 500 internal server error including the following stack trace:

30-Oct-2017 18:07:43.717 INFO [http-nio-8080-exec-2] mx.nic.rdap.sql.model.IpNetworkModel.getByDomainId Executing QUERY:com.mysql.jdbc.JDBC42PreparedStatement@5d8256d1:  SELECT ipn.ine_id, ipn.ine_handle, ipn.ine_parent_handle, ipn.ip_version_id, ipn.ine_start_address_down, ipn.ine_end_address_down, ipn.ine_start_address_up, ipn.ine_end_address_up, ipn.ine_name, ipn.ine_type, ipn.ccd_id, ipn.ine_port43, ipn.ine_cidr FROM rdap.ip_network ipn JOIN rdap.domain_networks dom ON dom.ine_id = ipn.ine_id WHERE dom.dom_id = 802;
30-Oct-2017 18:07:43.728 SEVERE [http-nio-8080-exec-2] mx.nic.rdap.server.result.ExceptionResult.<init> java.lang.NullPointerException
 javax.servlet.ServletException: java.lang.NullPointerException
	at org.apache.shiro.web.servlet.AdviceFilter.cleanup(AdviceFilter.java:196)
	at org.apache.shiro.web.filter.authc.AuthenticatingFilter.cleanup(AuthenticatingFilter.java:155)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:148)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1132)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at java.util.ArrayList.addAll(ArrayList.java:581)
	at mx.nic.rdap.core.db.VCard.setPostalInfo(VCard.java:233)
	at mx.nic.rdap.server.privacy.EntityPrivacyFilter.filterVcard(EntityPrivacyFilter.java:236)
	at mx.nic.rdap.server.privacy.EntityPrivacyFilter.filterEntity(EntityPrivacyFilter.java:57)
	at mx.nic.rdap.server.privacy.EntityPrivacyFilter.filterAnidatedEntities(EntityPrivacyFilter.java:160)
	at mx.nic.rdap.server.privacy.NameserverPrivacyFilter.filterNameserver(NameserverPrivacyFilter.java:90)
	at mx.nic.rdap.server.privacy.NameserverPrivacyFilter.filterAnidatedNameserver(NameserverPrivacyFilter.java:44)
	at mx.nic.rdap.server.privacy.DomainPrivacyFilter.filterDomain(DomainPrivacyFilter.java:76)
	at mx.nic.rdap.server.servlet.RdapServlet.renderResult(RdapServlet.java:101)
	at mx.nic.rdap.server.servlet.RdapServlet.doGet(RdapServlet.java:75)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	... 27 more

**Comment by dhfelix** [comment]
The way a List<> is set in the pojo was changed, to avoid the NPE

**Comment by TheRedTrainer** [comment]
Verified. If the vcard.postalInfo privacy setting is configured to be visible for nobody ("none"), the server hides this information. It doesn't throw a severe error anymore.

**Comment by pcarana** [comment]
Closing, fixed in Red Dog v1.2
